---
name: 'Docker Image CI'

# not sure why this even triggers `truthy`
# yamllint disable-line rule:truthy
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: 'actions/checkout@v2'
      - name: 'Build the Docker image'
        # yamllint disable rule:line-length
        run: |
          make docker-goflow
          # make docker-goflow GOFLOW_VERSION="${GITHUB_RUN_ID}" BUILDINFOSDET="${GITHUB_SHA}"
          # docker build . --file Dockerfile --tag docker.pkg.github.com/${GITHUB_REPOSITORY}/goflow:${GITHUB_RUN_ID}
          # docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/goflow:${GITHUB_RUN_ID}
        env:
          DOCKER_REPO: "docker.pkg.github.com/${GITHUB_REPOSITORY}/"
          GOFLOW_VERSION: "${GITHUB_RUN_ID}"
          BUILDINFOSDET: "${GITHUB_SHA}"
#   # yamllint enable rule:line-length
#   test:
#     runs-on: 'ubuntu-latest'
#     needs: 'build'
#     steps:
#       - name: 'Docker Login'
#         uses: 'azure/docker-login@v1'
#         with:
#           login-server: 'docker.pkg.github.com'
#           username: $GITHUB_ACTOR
#           password: ${{ secrets.GITHUB_TOKEN }}
#       - uses: 'e1himself/goss-installation-action@v1'
#       - uses: 'actions/checkout@v2'
#       - name: 'Test the Docker image'
#         # yamllint disable rule:line-length
#         run: |
#           export GOSS_FILES_STRATEGY=cp
#           export GOSS_SLEEP=5
#           dgoss run -it docker.pkg.github.com/${GITHUB_REPOSITORY}/goflow:${GITHUB_RUN_ID}
